/** George's Palabra del día list, in order. Days 1–60, then 61–120.
 *  word: unaccented, uppercase, ñ kept (JABON, NIÑOS, SEÑOR) — this is what matching uses.
 *  display: accented spelling for the reveal (jabón, árbol, señor).
 *  es / en: the one-line sentence and its gloss, copied as written.
 *  subjunctive: present on every third day (3, 6, …, 120).
 */
export const WORDLE_ANSWERS = [
  { word: "CALLE", display: "calle", es: "Vivo en la calle Hospicio.", en: "I live on Hospicio Street." },
  { word: "PLAZA", display: "plaza", es: "Nos vemos en la plaza a las seis.", en: "See you in the square at six." },
  { word: "VENGA", display: "venga", es: "Espero que el plomero venga hoy.", en: "I hope the plumber comes today.", subjunctive: true },
  { word: "LLAVE", display: "llave", es: "No encuentro la llave de la casa.", en: "I can't find the house key." },
  { word: "TACOS", display: "tacos", es: "Vamos por unos tacos al pastor.", en: "Let's go get some tacos al pastor." },
  { word: "TENGA", display: "tenga", es: "Ojalá que el hotel tenga agua caliente.", en: "I hope the hotel has hot water.", subjunctive: true },
  { word: "QUESO", display: "queso", es: "Quiero una quesadilla con queso.", en: "I want a quesadilla with cheese." },
  { word: "FERIA", display: "feria", es: "¿Traes feria para el camión?", en: "Do you have change for the bus?" },
  { word: "PUEDA", display: "pueda", es: "Me alegra que tu mamá pueda venir.", en: "I'm glad your mom can come.", subjunctive: true },
  { word: "LECHE", display: "leche", es: "Se acabó la leche.", en: "We're out of milk." },
  { word: "HUEVO", display: "huevo", es: "Quiero un huevo estrellado.", en: "I want a fried egg." },
  { word: "HAGAS", display: "hagas", es: "Te pido que hagas la reservación.", en: "I'm asking you to make the reservation.", subjunctive: true },
  { word: "CARTA", display: "carta", es: "¿Me trae la carta, por favor?", en: "Could you bring me the menu?" },
  { word: "BANCO", display: "banco", es: "El banco cierra a las cuatro.", en: "The bank closes at four." },
  { word: "DIGAS", display: "digas", es: "No quiero que le digas nada.", en: "I don't want you to tell him anything.", subjunctive: true },
  { word: "HOTEL", display: "hotel", es: "El hotel está a dos cuadras.", en: "The hotel is two blocks away." },
  { word: "CIELO", display: "cielo", es: "Qué bonito está el cielo hoy.", en: "The sky is so pretty today." },
  { word: "SEPAS", display: "sepas", es: "Es bueno que sepas manejar.", en: "It's good that you know how to drive.", subjunctive: true },
  { word: "JABON", display: "jabón", es: "Ya no hay jabón en el baño.", en: "There's no more soap in the bathroom." },
  { word: "SILLA", display: "silla", es: "¿Está ocupada esta silla?", en: "Is this chair taken?" },
  { word: "VAYAS", display: "vayas", es: "Quiero que vayas conmigo al mercado.", en: "I want you to go to the market with me.", subjunctive: true },
  { word: "RENTA", display: "renta", es: "La renta se paga el día primero.", en: "Rent is due on the first." },
  { word: "MUSEO", display: "museo", es: "El museo abre los domingos.", en: "The museum opens on Sundays." },
  { word: "SALGA", display: "salga", es: "Espero que el camión salga a tiempo.", en: "I hope the bus leaves on time.", subjunctive: true },
  { word: "PAPEL", display: "papel", es: "Se acabó el papel de baño.", en: "We're out of toilet paper." },
  { word: "NIÑOS", display: "niños", es: "Los niños juegan en el parque.", en: "The kids play in the park." },
  { word: "PONGA", display: "ponga", es: "Dígale que ponga la mesa.", en: "Tell him to set the table.", subjunctive: true },
  { word: "SUEÑO", display: "sueño", es: "Tengo mucho sueño.", en: "I'm really sleepy." },
  { word: "PEDIR", display: "pedir", es: "Voy a pedir la cuenta.", en: "I'm going to ask for the check." },
  { word: "HAYAN", display: "hayan", es: "Espero que hayan llegado bien.", en: "I hope you all got there safely.", subjunctive: true },
  { word: "PAGAR", display: "pagar", es: "¿Puedo pagar con tarjeta?", en: "Can I pay by card?" },
  { word: "SALIR", display: "salir", es: "Hay que salir temprano.", en: "We have to leave early." },
  { word: "SEPAN", display: "sepan", es: "Quiero que todos sepan la verdad.", en: "I want everyone to know the truth.", subjunctive: true },
  { word: "TOMAR", display: "tomar", es: "¿Qué quieres tomar?", en: "What do you want to drink?" },
  { word: "DULCE", display: "dulce", es: "Este pan está muy dulce.", en: "This bread is very sweet." },
  { word: "VAYAN", display: "vayan", es: "Ojalá que vayan a la fiesta.", en: "I hope you all go to the party.", subjunctive: true },
  { word: "LIMON", display: "limón", es: "Una cerveza con limón, por favor.", en: "A beer with lime, please." },
  { word: "MANGO", display: "mango", es: "El mango está en temporada.", en: "Mango is in season." },
  { word: "DIGAN", display: "digan", es: "No creo que digan la verdad.", en: "I don't think they're telling the truth.", subjunctive: true },
  { word: "POLLO", display: "pollo", es: "Quiero la sopa de pollo.", en: "I want the chicken soup." },
  { word: "CARNE", display: "carne", es: "La carne asada está lista.", en: "The grilled beef is ready." },
  { word: "HAGAN", display: "hagan", es: "Pídeles que hagan menos ruido.", en: "Ask them to make less noise.", subjunctive: true },
  { word: "ARROZ", display: "arroz", es: "El arroz viene con frijoles.", en: "The rice comes with beans." },
  { word: "AMIGO", display: "amigo", es: "Te presento a mi amigo Luis.", en: "This is my friend Luis." },
  { word: "ESTES", display: "estés", es: "Me alegra que estés aquí.", en: "I'm glad you're here.", subjunctive: true },
  { word: "SALUD", display: "salud", es: "¡Salud por los nuevos vecinos!", en: "Cheers to the new neighbors!" },
  { word: "FELIZ", display: "feliz", es: "Estoy feliz de verte.", en: "I'm happy to see you." },
  { word: "PIDAS", display: "pidas", es: "No hace falta que pidas permiso.", en: "You don't need to ask permission.", subjunctive: true },
  { word: "CERCA", display: "cerca", es: "¿Hay una farmacia cerca?", en: "Is there a pharmacy nearby?" },
  { word: "LEJOS", display: "lejos", es: "El aeropuerto está lejos.", en: "The airport is far away." },
  { word: "QUEPA", display: "quepa", es: "Dudo que quepa todo en la maleta.", en: "I doubt everything will fit in the suitcase.", subjunctive: true },
  { word: "TARDE", display: "tarde", es: "Perdón, llegué tarde.", en: "Sorry I'm late." },
  { word: "NOCHE", display: "noche", es: "Salimos a cenar esta noche.", en: "We're going out to dinner tonight." },
  { word: "OIGAS", display: "oigas", es: "Me preocupa que no me oigas.", en: "I'm worried you can't hear me.", subjunctive: true },
  { word: "LUNES", display: "lunes", es: "Nos vemos el lunes.", en: "See you Monday." },
  { word: "ENERO", display: "enero", es: "Llegamos en enero.", en: "We arrive in January." },
  { word: "PAGUE", display: "pague", es: "Prefiero que la empresa pague el taxi.", en: "I'd rather the company pay for the taxi.", subjunctive: true },
  { word: "PLAYA", display: "playa", es: "Este verano vamos a la playa.", en: "This summer we're going to the beach." },
  { word: "CARRO", display: "carro", es: "Dejé el carro en la esquina.", en: "I left the car on the corner." },
  { word: "SIGAS", display: "sigas", es: "Te recomiendo que sigas derecho dos cuadras.", en: "I suggest you go straight for two blocks.", subjunctive: true },
  { word: "FRUTA", display: "fruta", es: "Compré fruta en el mercado.", en: "I bought fruit at the market." },
  { word: "PERRO", display: "perro", es: "Mi perro duerme en el patio.", en: "My dog sleeps in the backyard." },
  { word: "HABLE", display: "hable", es: "Quiero que el doctor hable más despacio.", en: "I want the doctor to speak more slowly.", subjunctive: true },
  { word: "LIBRO", display: "libro", es: "Estoy leyendo un libro en español.", en: "I'm reading a book in Spanish." },
  { word: "MUNDO", display: "mundo", es: "Todo el mundo come aquí.", en: "Everybody eats here." },
  { word: "LLAME", display: "llame", es: "Dile que me llame mañana.", en: "Tell her to call me tomorrow.", subjunctive: true },
  { word: "MADRE", display: "madre", es: "Mi madre hace el mejor mole.", en: "My mother makes the best mole." },
  { word: "PADRE", display: "padre", es: "¡Qué padre está tu casa!", en: "Your house is so cool!" },
  { word: "TOMES", display: "tomes", es: "Es importante que tomes mucha agua.", en: "It's important that you drink a lot of water.", subjunctive: true },
  { word: "RELOJ", display: "reloj", es: "Se me olvidó el reloj en el hotel.", en: "I left my watch at the hotel." },
  { word: "METRO", display: "metro", es: "Vamos en metro al centro.", en: "Let's take the subway downtown." },
  { word: "CREAS", display: "creas", es: "Aunque no lo creas, ya aprendí a cocinar.", en: "Believe it or not, I've learned to cook.", subjunctive: true },
  { word: "VERDE", display: "verde", es: "Prefiero la salsa verde.", en: "I prefer the green salsa." },
  { word: "NEGRO", display: "negro", es: "Un café negro, por favor.", en: "A black coffee, please." },
  { word: "HAYAS", display: "hayas", es: "Qué bueno que hayas venido.", en: "I'm so glad you came.", subjunctive: true },
  { word: "SALSA", display: "salsa", es: "¿Esta salsa pica mucho?", en: "Is this salsa very spicy?" },
  { word: "CHILE", display: "chile", es: "Sin chile, por favor.", en: "No chili, please." },
  { word: "ESTEN", display: "estén", es: "Espero que todos estén bien.", en: "I hope everyone is well.", subjunctive: true },
  { word: "ELOTE", display: "elote", es: "Me compré un elote con limón y chile.", en: "I got myself an elote with lime and chili." },
  { word: "FRESA", display: "fresa", es: "Un licuado de fresa, por favor.", en: "A strawberry smoothie, please." },
  { word: "PIDAN", display: "pidan", es: "Diles que pidan la cuenta.", en: "Tell them to ask for the check.", subjunctive: true },
  { word: "SEÑOR", display: "señor", es: "Disculpe, señor, ¿dónde está la parada?", en: "Excuse me, sir, where's the stop?" },
  { word: "DUEÑO", display: "dueño", es: "El dueño del restaurante es muy amable.", en: "The restaurant owner is very kind." },
  { word: "SIGAN", display: "sigan", es: "Les pido que sigan al guía.", en: "I ask you all to follow the guide.", subjunctive: true },
  { word: "MARZO", display: "marzo", es: "Mi cumpleaños es en marzo.", en: "My birthday is in March." },
  { word: "ABRIL", display: "abril", es: "En abril hace mucho calor.", en: "It's very hot in April." },
  { word: "OIGAN", display: "oigan", es: "Habla más fuerte para que te oigan.", en: "Speak louder so they can hear you.", subjunctive: true },
  { word: "JULIO", display: "julio", es: "En julio llueve casi todas las tardes.", en: "In July it rains almost every afternoon." },
  { word: "BOLSA", display: "bolsa", es: "¿Me da una bolsa, por favor?", en: "Could I have a bag, please?" },
  { word: "DUELA", display: "duela", es: "No creo que te duela mucho.", en: "I don't think it'll hurt you much.", subjunctive: true },
  { word: "TECHO", display: "techo", es: "Cenamos en el techo de la casa.", en: "We had dinner on the roof of the house." },
  { word: "PATIO", display: "patio", es: "Hay una fuente en el patio.", en: "There's a fountain in the courtyard." },
  { word: "SIRVA", display: "sirva", es: "Ojalá que te sirva el mapa.", en: "I hope the map helps you.", subjunctive: true },
  { word: "ARBOL", display: "árbol", es: "Nos sentamos debajo de un árbol.", en: "We sat under a tree." },
  { word: "CALOR", display: "calor", es: "Hace mucho calor hoy.", en: "It's really hot today." },
  { word: "GUSTE", display: "guste", es: "Espero que te guste la comida.", en: "I hope you like the food.", subjunctive: true },
  { word: "NUBES", display: "nubes", es: "Hay nubes, pero no va a llover.", en: "It's cloudy, but it's not going to rain." },
  { word: "PLATO", display: "plato", es: "Este plato es para compartir.", en: "This dish is for sharing." },
  { word: "DEJES", display: "dejes", es: "No dejes la puerta abierta.", en: "Don't leave the door open.", subjunctive: true },
  { word: "FALDA", display: "falda", es: "Me gusta tu falda nueva.", en: "I like your new skirt." },
  { word: "PRIMO", display: "primo", es: "Mi primo vive en Querétaro.", en: "My cousin lives in Querétaro." },
  { word: "CAIGA", display: "caiga", es: "Cuidado, no quiero que se caiga el pastel.", en: "Careful, I don't want the cake to fall.", subjunctive: true },
  { word: "NOVIA", display: "novia", es: "Te presento a mi novia, Ana.", en: "This is my girlfriend, Ana." },
  { word: "VIAJE", display: "viaje", es: "¡Buen viaje!", en: "Have a good trip!" },
  { word: "LLEVE", display: "lleve", es: "Pídele al taxista que nos lleve al centro.", en: "Ask the taxi driver to take us downtown.", subjunctive: true },
  { word: "AVION", display: "avión", es: "El avión sale a las ocho.", en: "The plane leaves at eight." },
  { word: "BEBER", display: "beber", es: "¿Algo de beber?", en: "Something to drink?" },
  { word: "CUIDE", display: "cuide", es: "Le pedí a mi vecina que cuide al perro.", en: "I asked my neighbor to look after the dog.", subjunctive: true },
  { word: "NADAR", display: "nadar", es: "Vamos a nadar en la alberca.", en: "Let's go swimming in the pool." },
  { word: "JUGAR", display: "jugar", es: "¿Quieres jugar fútbol el sábado?", en: "Do you want to play soccer on Saturday?" },
  { word: "ABRAS", display: "abras", es: "No abras la ventana, hace frío.", en: "Don't open the window, it's cold.", subjunctive: true },
  { word: "LAVAR", display: "lavar", es: "Tengo que lavar la ropa.", en: "I have to do the laundry." },
  { word: "SUCIO", display: "sucio", es: "Este vaso está sucio.", en: "This glass is dirty." },
  { word: "VENDA", display: "venda", es: "Busco una tienda que venda tarjetas SIM.", en: "I'm looking for a store that sells SIM cards.", subjunctive: true },
  { word: "LLENO", display: "lleno", es: "Ya estoy lleno, gracias.", en: "I'm full, thanks." },
  { word: "NUEVO", display: "nuevo", es: "¿Qué hay de nuevo?", en: "What's new?" },
  { word: "TOQUE", display: "toque", es: "Espero que la banda toque otra canción.", en: "I hope the band plays another song.", subjunctive: true },
  { word: "LISTO", display: "listo", es: "¿Ya estás listo?", en: "Are you ready yet?" },
  { word: "FACIL", display: "fácil", es: "No es fácil, pero vale la pena.", en: "It's not easy, but it's worth it." },
  { word: "PASEN", display: "pasen", es: "Quiero que pasen una noche increíble.", en: "I want you all to have an amazing night.", subjunctive: true },
];
