/** George's final 60-day Palabra del día list, in order.
 *  word: unaccented, uppercase, ñ kept (JABON, NIÑOS, SUEÑO) — this is what matching uses.
 *  display: accented spelling for the reveal (jabón, limón, estés).
 *  es / en: the one-line sentence and its gloss.
 */
export const WORDLE_ANSWERS = [
  { word: "CALLE", display: "calle", es: "Vivo en la calle Hospicio.", en: "I live on Hospicio Street." },
  { word: "PLAZA", display: "plaza", es: "Nos vemos en la plaza a las seis.", en: "See you in the square at six." },
  { word: "VENGA", display: "venga", es: "Espero que el plomero venga hoy.", en: "I hope the plumber comes today." },
  { word: "LLAVE", display: "llave", es: "No encuentro la llave de la casa.", en: "I can't find the house key." },
  { word: "TACOS", display: "tacos", es: "Vamos por unos tacos al pastor.", en: "Let's go get some tacos al pastor." },
  { word: "TENGA", display: "tenga", es: "Ojalá que el hotel tenga agua caliente.", en: "I hope the hotel has hot water." },
  { word: "QUESO", display: "queso", es: "Quiero una quesadilla con queso.", en: "I want a quesadilla with cheese." },
  { word: "FERIA", display: "feria", es: "¿Traes feria para el camión?", en: "Do you have change for the bus?" },
  { word: "PUEDA", display: "pueda", es: "Me alegra que tu mamá pueda venir.", en: "I'm glad your mom can come." },
  { word: "LECHE", display: "leche", es: "Se acabó la leche.", en: "We're out of milk." },
  { word: "HUEVO", display: "huevo", es: "Quiero un huevo estrellado.", en: "I want a fried egg." },
  { word: "HAGAS", display: "hagas", es: "Te pido que hagas la reservación.", en: "I'm asking you to make the reservation." },
  { word: "CARTA", display: "carta", es: "¿Me trae la carta, por favor?", en: "Could you bring me the menu?" },
  { word: "BANCO", display: "banco", es: "El banco cierra a las cuatro.", en: "The bank closes at four." },
  { word: "DIGAS", display: "digas", es: "No quiero que le digas nada.", en: "I don't want you to tell him anything." },
  { word: "HOTEL", display: "hotel", es: "El hotel está a dos cuadras.", en: "The hotel is two blocks away." },
  { word: "CIELO", display: "cielo", es: "Qué bonito está el cielo hoy.", en: "The sky is so pretty today." },
  { word: "SEPAS", display: "sepas", es: "Es bueno que sepas manejar.", en: "It's good that you know how to drive." },
  { word: "JABON", display: "jabón", es: "Ya no hay jabón en el baño.", en: "There's no more soap in the bathroom." },
  { word: "SILLA", display: "silla", es: "¿Está ocupada esta silla?", en: "Is this chair taken?" },
  { word: "VAYAS", display: "vayas", es: "Quiero que vayas conmigo al mercado.", en: "I want you to go to the market with me." },
  { word: "RENTA", display: "renta", es: "La renta se paga el día primero.", en: "Rent is due on the first." },
  { word: "MUSEO", display: "museo", es: "El museo abre los domingos.", en: "The museum opens on Sundays." },
  { word: "SALGA", display: "salga", es: "Espero que el camión salga a tiempo.", en: "I hope the bus leaves on time." },
  { word: "PAPEL", display: "papel", es: "Se acabó el papel de baño.", en: "We're out of toilet paper." },
  { word: "NIÑOS", display: "niños", es: "Los niños juegan en el jardín.", en: "The kids play in the garden." },
  { word: "PONGA", display: "ponga", es: "Dígale que ponga la mesa.", en: "Tell him to set the table." },
  { word: "SUEÑO", display: "sueño", es: "Tengo mucho sueño.", en: "I'm really sleepy." },
  { word: "PEDIR", display: "pedir", es: "Voy a pedir la cuenta.", en: "I'm going to ask for the check." },
  { word: "HAYAN", display: "hayan", es: "Espero que hayan llegado bien.", en: "I hope you all got there safely." },
  { word: "PAGAR", display: "pagar", es: "¿Puedo pagar con tarjeta?", en: "Can I pay by card?" },
  { word: "SALIR", display: "salir", es: "Hay que salir temprano.", en: "We have to leave early." },
  { word: "SEPAN", display: "sepan", es: "Quiero que todos sepan la verdad.", en: "I want everyone to know the truth." },
  { word: "TOMAR", display: "tomar", es: "¿Qué quieres tomar?", en: "What do you want to drink?" },
  { word: "DULCE", display: "dulce", es: "Este pan está muy dulce.", en: "This bread is very sweet." },
  { word: "VAYAN", display: "vayan", es: "Ojalá que vayan a la fiesta.", en: "I hope you all go to the party." },
  { word: "LIMON", display: "limón", es: "Una cerveza con limón, por favor.", en: "A beer with lime, please." },
  { word: "MANGO", display: "mango", es: "El mango está en temporada.", en: "Mango is in season." },
  { word: "DIGAN", display: "digan", es: "No creo que digan la verdad.", en: "I don't think they're telling the truth." },
  { word: "POLLO", display: "pollo", es: "Quiero la sopa de pollo.", en: "I want the chicken soup." },
  { word: "CARNE", display: "carne", es: "La carne asada está lista.", en: "The grilled beef is ready." },
  { word: "HAGAN", display: "hagan", es: "Pídeles que hagan menos ruido.", en: "Ask them to make less noise." },
  { word: "ARROZ", display: "arroz", es: "El arroz viene con frijoles.", en: "The rice comes with beans." },
  { word: "AMIGO", display: "amigo", es: "Te presento a mi amigo Luis.", en: "This is my friend Luis." },
  { word: "ESTES", display: "estés", es: "Me alegra que estés aquí.", en: "I'm glad you're here." },
  { word: "SALUD", display: "salud", es: "¡Salud por los nuevos vecinos!", en: "Cheers to the new neighbors!" },
  { word: "FELIZ", display: "feliz", es: "Estoy feliz de verte.", en: "I'm happy to see you." },
  { word: "PIDAS", display: "pidas", es: "No hace falta que pidas permiso.", en: "You don't need to ask permission." },
  { word: "CERCA", display: "cerca", es: "¿Hay una farmacia cerca?", en: "Is there a pharmacy nearby?" },
  { word: "LEJOS", display: "lejos", es: "El aeropuerto está lejos.", en: "The airport is far away." },
  { word: "QUEPA", display: "quepa", es: "Dudo que quepa todo en la maleta.", en: "I doubt everything will fit in the suitcase." },
  { word: "TARDE", display: "tarde", es: "Perdón, llegué tarde.", en: "Sorry I'm late." },
  { word: "NOCHE", display: "noche", es: "Salimos a cenar esta noche.", en: "We're going out to dinner tonight." },
  { word: "OIGAS", display: "oigas", es: "Me preocupa que no me oigas.", en: "I'm worried you can't hear me." },
  { word: "LUNES", display: "lunes", es: "Nos vemos el lunes.", en: "See you Monday." },
  { word: "ENERO", display: "enero", es: "Llegamos en enero.", en: "We arrive in January." },
  { word: "PAGUE", display: "pague", es: "Prefiero que la empresa pague el taxi.", en: "I'd rather the company pay for the taxi." },
  { word: "PLAYA", display: "playa", es: "Este verano vamos a la playa.", en: "This summer we're going to the beach." },
  { word: "CARRO", display: "carro", es: "Dejé el carro en la esquina.", en: "I left the car on the corner." },
  { word: "SIGAS", display: "sigas", es: "Te recomiendo que sigas derecho dos cuadras.", en: "I suggest you go straight for two blocks." },
];
